/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as DoneRouteImport } from './routes/done'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminSeniorRouteImport } from './routes/_authenticated.admin.senior'
import { Route as AuthenticatedAdminRound2RouteImport } from './routes/_authenticated.admin.round2'
import { Route as AuthenticatedAdminMonitorRouteImport } from './routes/_authenticated.admin.monitor'
import { Route as AuthenticatedAdminJuniorRouteImport } from './routes/_authenticated.admin.junior'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSeniorRoute =
  AuthenticatedAdminSeniorRouteImport.update({
    id: '/senior',
    path: '/senior',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRound2Route =
  AuthenticatedAdminRound2RouteImport.update({
    id: '/round2',
    path: '/round2',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonitorRoute =
  AuthenticatedAdminMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJuniorRoute =
  AuthenticatedAdminJuniorRouteImport.update({
    id: '/junior',
    path: '/junior',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/done': typeof DoneRoute
  '/entry': typeof EntryRoute
  '/quiz': typeof QuizRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/junior': typeof AuthenticatedAdminJuniorRoute
  '/admin/monitor': typeof AuthenticatedAdminMonitorRoute
  '/admin/round2': typeof AuthenticatedAdminRound2Route
  '/admin/senior': typeof AuthenticatedAdminSeniorRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/done': typeof DoneRoute
  '/entry': typeof EntryRoute
  '/quiz': typeof QuizRoute
  '/admin/junior': typeof AuthenticatedAdminJuniorRoute
  '/admin/monitor': typeof AuthenticatedAdminMonitorRoute
  '/admin/round2': typeof AuthenticatedAdminRound2Route
  '/admin/senior': typeof AuthenticatedAdminSeniorRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/done': typeof DoneRoute
  '/entry': typeof EntryRoute
  '/quiz': typeof QuizRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/junior': typeof AuthenticatedAdminJuniorRoute
  '/_authenticated/admin/monitor': typeof AuthenticatedAdminMonitorRoute
  '/_authenticated/admin/round2': typeof AuthenticatedAdminRound2Route
  '/_authenticated/admin/senior': typeof AuthenticatedAdminSeniorRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/done'
    | '/entry'
    | '/quiz'
    | '/admin'
    | '/admin/junior'
    | '/admin/monitor'
    | '/admin/round2'
    | '/admin/senior'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/done'
    | '/entry'
    | '/quiz'
    | '/admin/junior'
    | '/admin/monitor'
    | '/admin/round2'
    | '/admin/senior'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/done'
    | '/entry'
    | '/quiz'
    | '/_authenticated/admin'
    | '/_authenticated/admin/junior'
    | '/_authenticated/admin/monitor'
    | '/_authenticated/admin/round2'
    | '/_authenticated/admin/senior'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DoneRoute: typeof DoneRoute
  EntryRoute: typeof EntryRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/senior': {
      id: '/_authenticated/admin/senior'
      path: '/senior'
      fullPath: '/admin/senior'
      preLoaderRoute: typeof AuthenticatedAdminSeniorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/round2': {
      id: '/_authenticated/admin/round2'
      path: '/round2'
      fullPath: '/admin/round2'
      preLoaderRoute: typeof AuthenticatedAdminRound2RouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monitor': {
      id: '/_authenticated/admin/monitor'
      path: '/monitor'
      fullPath: '/admin/monitor'
      preLoaderRoute: typeof AuthenticatedAdminMonitorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/junior': {
      id: '/_authenticated/admin/junior'
      path: '/junior'
      fullPath: '/admin/junior'
      preLoaderRoute: typeof AuthenticatedAdminJuniorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminJuniorRoute: typeof AuthenticatedAdminJuniorRoute
  AuthenticatedAdminMonitorRoute: typeof AuthenticatedAdminMonitorRoute
  AuthenticatedAdminRound2Route: typeof AuthenticatedAdminRound2Route
  AuthenticatedAdminSeniorRoute: typeof AuthenticatedAdminSeniorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminJuniorRoute: AuthenticatedAdminJuniorRoute,
  AuthenticatedAdminMonitorRoute: AuthenticatedAdminMonitorRoute,
  AuthenticatedAdminRound2Route: AuthenticatedAdminRound2Route,
  AuthenticatedAdminSeniorRoute: AuthenticatedAdminSeniorRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DoneRoute: DoneRoute,
  EntryRoute: EntryRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
