// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types'

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL;

  const SUPABASE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  console.log("SUPABASE_URL:", SUPABASE_URL);
  console.log("SUPABASE_KEY:", SUPABASE_KEY);

  if (!SUPABASE_URL || !SUPABASE_KEY) {
    throw new Error(
      "Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY"
    );
  }

  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_KEY,
    {
      auth: {
        storage:
          typeof window !== "undefined"
            ? localStorage
            : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );
}
let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

